name: plural-ci

on:
  push:
    branches: [ master ]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: actions/checkout@v3
    - uses: google-github-actions/auth@v0
      with:
        workload_identity_provider: 'projects/${{ secrets.GOOGLE_PROJECT_ID }}/locations/global/workloadIdentityPools/github/providers/github'
        service_account: 'terraform@pluralsh.iam.gserviceaccount.com'
        token_format: 'access_token'
        create_credentials_file: true
    - uses: google-github-actions/setup-gcloud@v0.3.0
    - name: Login to gcr
      run: gcloud auth configure-docker -q
    - name: Login to plural registry
      uses: docker/login-action@v1
      with:
        registry: dkr.plural.sh
        username: mjg@plural.sh
        password: ${{ secrets.PLURAL_ACCESS_TOKEN }}
    - run: make build
    - run: make push
  publish-cloud:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: actions/checkout@v3
    - uses: google-github-actions/auth@v0
      with:
        workload_identity_provider: 'projects/${{ secrets.GOOGLE_PROJECT_ID }}/locations/global/workloadIdentityPools/github/providers/github'
        service_account: 'terraform@pluralsh.iam.gserviceaccount.com'
        token_format: 'access_token'
        create_credentials_file: true
    - uses: google-github-actions/setup-gcloud@v0.3.0
    - name: Login to gcr
      run: gcloud auth configure-docker -q
    - name: Login to plural registry
      uses: docker/login-action@v1
      with:
        registry: dkr.plural.sh
        username: mjg@plural.sh
        password: ${{ secrets.PLURAL_ACCESS_TOKEN }}
    - run: make build-cloud
    - run: make push-cloud
  # deploy:
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/master'
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-go@v2
  #     with:
  #       go-version: '^1.17.1'
  #   - uses: hashicorp/setup-terraform@v1
  #   - uses: azure/setup-helm@v1
  #     with:
  #       version: latest
  #   - name: installing plural
  #     uses: pluralsh/setup-plural@v0.1.2
  #     with:
  #       config: ${{ secrets.PLURAL_CONF }}
  #   - run: plural apply
